/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/zPSAXDE2cp5
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableHeader,
  TableRow,
  TableHead,
  TableBody,
  TableCell,
} from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";

const diagnosticPaper: React.FC = () => {
  return (
    <div className="p-4 space-y-4">
      <header className="text-center">
        <h1 className="text-2xl font-bold text-green-700">
          SAFE-SIGHT EYE CARE
        </h1>
        <p>An excellent eye care centre</p>
        <p>Kiyam Siphai Babu Bazar, Thoubal, Manipur-795138</p>
        <p>03848 291288 (Call) / 8257970103</p>
        <p>safeeyeclinic@gmail.com</p>
      </header>
      <section className="border-t border-b py-2">
        <h2 className="text-lg font-bold">Prescription (Rx)</h2>
        <div className="grid grid-cols-2 gap-4">
          <div>
            <p>Patient ID:</p>
            <p>Name:</p>
            <p>Address:</p>
          </div>
          <div>
            <p>Age: 52 yrs.</p>
            <p>Sex: Female</p>
            <p>Mobile:</p>
          </div>
        </div>
      </section>
      <section className="border-t border-b py-2">
        <h2 className="text-lg font-bold">Complaint</h2>
        <div className="space-y-2">
          <div className="flex items-center space-x-2">
            <span>1.</span>
            <Label htmlFor="complaint1-eye">Eye:</Label>
            <Select id="complaint1-eye">
              <SelectTrigger>
                <SelectValue placeholder="OU" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="OU">OU</SelectItem>
                <SelectItem value="OS">OS</SelectItem>
                <SelectItem value="OD">OD</SelectItem>
              </SelectContent>
            </Select>
            <Label htmlFor="complaint1-type">Complaint:</Label>
            <Select id="complaint1-type">
              <SelectTrigger>
                <SelectValue placeholder="Select Complaint" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="Headache">Headache</SelectItem>
                <SelectItem value="Blurred Vision">Blurred Vision</SelectItem>
              </SelectContent>
            </Select>
            <div className="flex items-center space-x-2">
              <Label>Duration:</Label>
              <Input placeholder="Number" className="w-16" />
              <span>x</span>
              <Select>
                <SelectTrigger id="duration1">
                  <SelectValue placeholder="Hours" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Hours">Hours</SelectItem>
                  <SelectItem value="Days">Days</SelectItem>
                  <SelectItem value="Weeks">Weeks</SelectItem>
                  <SelectItem value="Months">Months</SelectItem>
                  <SelectItem value="Years">Years</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <Button variant="destructive">Remove</Button>
          </div>
          <Button>Add Complaint</Button>
        </div>
      </section>
      <section className="border-t border-b py-2">
        <h2 className="text-lg font-bold">Diagnosis</h2>
        <div className="space-y-2">
          <div className="flex items-center space-x-2">
            <span>1.</span>
            <Select>
              <SelectTrigger>
                <SelectValue placeholder="OU" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="OU">OU</SelectItem>
              </SelectContent>
            </Select>
            <Input placeholder="Presbyopia" className="w-32" />
            <Button variant="destructive">Remove</Button>
          </div>
          <div className="flex items-center space-x-2">
            <span>2.</span>
            <Select>
              <SelectTrigger id="diagnosis2">
                <SelectValue placeholder="OU" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="OU">OU</SelectItem>
              </SelectContent>
            </Select>
            <Input placeholder="Ocular Allergy" className="w-40" />
            <Button variant="destructive">Remove</Button>
          </div>
          <Button>Add Diagnosis</Button>
        </div>
      </section>
      <section className="border-t border-b py-2">
        <h2 className="text-lg font-bold">Glass Prescription</h2>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Right eye</TableHead>
              <TableHead>Left eye</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow className="flex">
              <TableCell className="flex-1">
                <p className="font-bold">DV</p>
                <Input placeholder="SPH" className="w-20" />
                <Input placeholder="CYL" className="w-20" />
                <Input placeholder="Axis" className="w-20" />
                <Input placeholder="V/A" className="w-20" />
              </TableCell>
              <TableCell className="flex-1">
                <p className="font-bold">DV</p>
                <Input placeholder="SPH" className="w-20" />
                <Input placeholder="CYL" className="w-20" />
                <Input placeholder="Axis" className="w-20" />
                <Input placeholder="V/A" className="w-20" />
              </TableCell>
            </TableRow>
            <TableRow className="flex">
              <TableCell className="flex-1">
                <p className="font-bold">NV</p>
                <Input placeholder="SPH" className="w-20" />
                <Input placeholder="CYL" className="w-20" />
                <Input placeholder="Axis" className="w-20" />
                <Input placeholder="V/A" className="w-20" />
              </TableCell>
              <TableCell className="flex-1">
                <p className="font-bold">NV</p>
                <Input placeholder="SPH" className="w-20" />
                <Input placeholder="CYL" className="w-20" />
                <Input placeholder="Axis" className="w-20" />
                <Input placeholder="V/A" className="w-20" />
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Glass Type</TableHead>
              <TableHead>Lens Type</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell>
                <Select>
                  <SelectTrigger id="glass-type-right">
                    <SelectValue placeholder="Right Eye" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="HardCoat">HardCoat</SelectItem>
                  </SelectContent>
                </Select>
              </TableCell>
              <TableCell>
                <Select>
                  <SelectTrigger id="lens-type-right">
                    <SelectValue placeholder="Right Eye" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Digital Progressive">
                      Digital Progressive
                    </SelectItem>
                  </SelectContent>
                </Select>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                <Select>
                  <SelectTrigger id="glass-type-left">
                    <SelectValue placeholder="Left Eye" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="HardCoat">HardCoat</SelectItem>
                  </SelectContent>
                </Select>
              </TableCell>
              <TableCell>
                <Select>
                  <SelectTrigger id="lens-type-left">
                    <SelectValue placeholder="Left Eye" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Digital Progressive">
                      Digital Progressive
                    </SelectItem>
                  </SelectContent>
                </Select>
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </section>
      <section className="border-t border-b py-2">
        <h2 className="text-lg font-bold">Review</h2>
        <div className="space-y-2">
          <div className="flex items-center space-x-2">
            <Label htmlFor="review">Review:</Label>
            <Textarea
              id="review"
              placeholder="Enter review here"
              className="flex-1"
            />
          </div>
          <div className="flex items-center space-x-2">
            <Label htmlFor="consultant">Consultant:</Label>
            <Input
              id="consultant"
              placeholder="Enter consultant name"
              className="flex-1"
            />
          </div>
          <div className="flex items-center space-x-2">
            <Label htmlFor="qualification">Qualification:</Label>
            <Input
              id="qualification"
              placeholder="Enter consultant qualification"
              className="flex-1"
            />
          </div>
          <div className="flex items-center space-x-2">
            <Label htmlFor="refer-to">Refer To:</Label>
            <Input
              id="refer-to"
              placeholder="Enter referral details"
              className="flex-1"
            />
          </div>
        </div>
      </section>
      <section className="border-t border-b py-2">
        <h2 className="text-lg font-bold">Clinical Comments</h2>
        <Textarea placeholder="Enter comments here" />
      </section>
      <section className="border-t border-b py-2">
        <h2 className="text-lg font-bold">Medications</h2>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Sl. No.</TableHead>
              <TableHead>Eye</TableHead>
              <TableHead>Form</TableHead>
              <TableHead>Medicine</TableHead>
              <TableHead>Dose</TableHead>
              <TableHead>Frequency</TableHead>
              <TableHead>Duration</TableHead>
              <TableHead>Remarks</TableHead>
              <TableHead>Action</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow className="flex">
              <TableCell className="flex-1">1</TableCell>
              <TableCell className="flex-1">
                <Select>
                  <SelectTrigger id="eye1">
                    <SelectValue placeholder="Both Eyes" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Both Eyes">Both Eyes</SelectItem>
                  </SelectContent>
                </Select>
              </TableCell>
              <TableCell className="flex-1">
                <Select>
                  <SelectTrigger id="form1">
                    <SelectValue placeholder="Eye Drop" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Eye Drop">Eye Drop</SelectItem>
                  </SelectContent>
                </Select>
              </TableCell>
              <TableCell className="flex-1">
                <Input placeholder="BEPONEL E/D Bepotastine 1.5% w/v" />
              </TableCell>
              <TableCell className="flex-1">
                <Input placeholder="1 drop" className="w-20" />
              </TableCell>
              <TableCell className="flex-1">
                <Input placeholder="4 times daily" className="w-20" />
              </TableCell>
              <TableCell className="flex-1">
                <div className="flex items-center space-x-2">
                  <Label>Duration:</Label>
                  <Input placeholder="Number" className="w-16" />
                  <span>x</span>
                  <Select>
                    <SelectTrigger id="duration1">
                      <SelectValue placeholder="Months" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="Hours">Hours</SelectItem>
                      <SelectItem value="Days">Days</SelectItem>
                      <SelectItem value="Weeks">Weeks</SelectItem>
                      <SelectItem value="Months">Months</SelectItem>
                      <SelectItem value="Years">Years</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </TableCell>
              <TableCell className="flex-1">
                <Input placeholder="Remarks" />
              </TableCell>
              <TableCell className="flex-1">
                <Button variant="destructive">Remove</Button>
              </TableCell>
            </TableRow>
            <TableRow className="flex">
              <TableCell className="flex-1">2</TableCell>
              <TableCell className="flex-1">
                <Select>
                  <SelectTrigger id="eye2">
                    <SelectValue placeholder="Both Eyes" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Both Eyes">Both Eyes</SelectItem>
                  </SelectContent>
                </Select>
              </TableCell>
              <TableCell className="flex-1">
                <Select>
                  <SelectTrigger id="form2">
                    <SelectValue placeholder="Eye Drop" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Eye Drop">Eye Drop</SelectItem>
                  </SelectContent>
                </Select>
              </TableCell>
              <TableCell className="flex-1">
                <Input placeholder="ARTELUB E/D Polyethylene Glycol 0.5% w/v" />
              </TableCell>
              <TableCell className="flex-1">
                <Input placeholder="1 drop" className="w-20" />
              </TableCell>
              <TableCell className="flex-1">
                <Input placeholder="4 times daily" className="w-20" />
              </TableCell>
              <TableCell className="flex-1">
                <div className="flex items-center space-x-2">
                  <Label>Duration:</Label>
                  <Input placeholder="Number" className="w-16" />
                  <span>x</span>
                  <Select>
                    <SelectTrigger id="duration2">
                      <SelectValue placeholder="Months" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="Hours">Hours</SelectItem>
                      <SelectItem value="Days">Days</SelectItem>
                      <SelectItem value="Weeks">Weeks</SelectItem>
                      <SelectItem value="Months">Months</SelectItem>
                      <SelectItem value="Years">Years</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </TableCell>
              <TableCell className="flex-1">
                <Input placeholder="Remarks" />
              </TableCell>
              <TableCell className="flex-1">
                <Button variant="destructive">Remove</Button>
              </TableCell>
            </TableRow>
            <TableRow className="flex">
              <TableCell className="flex-1">3</TableCell>
              <TableCell className="flex-1">
                <Select>
                  <SelectTrigger id="eye3">
                    <SelectValue placeholder="Both Eyes" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Both Eyes">Both Eyes</SelectItem>
                  </SelectContent>
                </Select>
              </TableCell>
              <TableCell className="flex-1">
                <Select>
                  <SelectTrigger id="form3">
                    <SelectValue placeholder="Capsule" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Capsule">Capsule</SelectItem>
                  </SelectContent>
                </Select>
              </TableCell>
              <TableCell className="flex-1">
                <Input placeholder="Cap. i-Zen Forte" />
              </TableCell>
              <TableCell className="flex-1">
                <Input placeholder="1 cap" />
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </section>
    </div>
  );
};

export default diagnosticPaper;
